version: '3'
services:
  php:
    image: thecodingmachine/php:7.4-v3-apache-node12
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: sf_stack
    command:
      'mysqld --innodb-flush-method=fsync'

volumes:
  mysql_data:
    driver: local