easy_admin:
  entities:
    User:
      class: App\Entity\User
      list:
        fields:
          - email
      form:
        fields:
          - email
          - { property: plainPassword, label: 'password', type: 'password' }
      new:
        fields:
          - active
